using System;
using System.Collections.Generic;
using System.Globalization;
namespace WordDeduction.UI
{
    public static class Copy
    {
        static readonly Dictionary<string, string[]> Text = new Dictionary<string, string[]> {
            {"kingsRecordInstruction", new[]{"Play at the table. Select only the person your group has actually eliminated.","Spielt am Tisch. Wählt nur die Person, die eure Gruppe tatsächlich herausgewählt hat."}},
            {"kingsConfirmTitle", new[]{"Eliminate this person?","Diese Person scheidet aus?"}},
            {"kingsConfirmHint", new[]{"Confirm the name before revealing the consequence. You can still change this selection.","Bestätigt den Namen, bevor die Folge aufgedeckt wird. Jetzt könnt ihr die Auswahl noch ändern."}},
            {"kingsNotKing", new[]{"Not a king","Kein König"}},
            {"kingsLastChanceTitle", new[]{"Last chance.","Letzte Chance."}},
            {"kingsLastChanceEntry", new[]{"Mr. White is the evil King. Pass the phone to this person for the last chance. The decision belongs to them alone, without team advice.","Mr. White ist der böse König. Gebt dieser Person das Handy für die Letzte Chance. Sie entscheidet allein, ohne Beratung durch ihr Team."}},
            {"kingsEvilWin", new[]{"The evil team wins.","Das böse Team gewinnt."}},
            {"kingsGoodWin", new[]{"The good team wins.","Das gute Team gewinnt."}},
            {"GoodKingEliminated", new[]{"The good King was eliminated.","Der gute König ist ausgeschieden."}},
            {"OnlyKingsRemain", new[]{"Only the two Kings remain.","Nur die beiden Könige sind noch dabei."}},
            {"kingsTeamResult", new[]{"Eliminated teammates share their team's result.","Ausgeschiedene teilen das Ergebnis ihres Teams."}},
            {"kingsGoodWord", new[]{"Good team's word","Wort des guten Teams"}},
            {"kingsEvilWord", new[]{"Evil team's word","Wort des bösen Teams"}},
            {"kingsFinalGoodKing", new[]{"Good King","Guter König"}},
            {"kingsFinalEvilKing", new[]{"Evil King · Mr. White","Böser König · Mr. White"}},
            {"kingsFinalGoodTeam", new[]{"Good team · Civilian","Gutes Team · Bürger"}},
            {"kingsFinalEvilTeam", new[]{"Evil team · Undercover","Böses Team · Undercover"}},
            {"kings", new[]{"Kings","Könige"}},
            {"kingsDescription", new[]{"Protect your leader. Find the other King. 5–20 players.","Schützt euren Anführer. Findet den anderen König. 5–20 Personen."}},
            {"kingsRoleMix", new[]{"{0} good incl. King · {1} Undercover + Mr. White","{0} Gute inkl. König · {1} Undercover + Mr. White"}},
            {"kingsUndercoverCount", new[]{"{0} Undercover","{0} Undercover"}},
            {"lessUndercover", new[]{"One fewer Undercover","Ein Undercover weniger"}},
            {"moreUndercover", new[]{"One more Undercover","Ein Undercover mehr"}},
            {"automaticUndercover", new[]{"Auto","Auto"}},
            {"automaticUndercoverHint", new[]{"Use the automatic Undercover count","Automatische Undercover-Anzahl verwenden"}},
            {"kingsCountAdjustment", new[]{"Using {0} for this group; your preference of {1} is saved.","Für diese Gruppe: {0}. Dein Wunsch von {1} bleibt gespeichert."}},
            {"goodKingPrivate", new[]{"You are the good King.","Du bist der gute König."}},
            {"evilKingPrivate", new[]{"Mr. White · evil King\nYou have no word.","Mr. White · böser König\nDu hast kein Wort."}},
            {"privateLeader", new[]{"Your leader\n{0}","Dein Anführer\n{0}"}},
            {"privateEvilNames", new[]{"The evil team","Das böse Team"}},
            {"privateTeamNames", new[]{"Your teammates","Deine Mitspieler"}},
            {"kingsHoldReveal", new[]{"Hold & slide","Halten & streichen"}},
            {"kingsDragHint", new[]{"Pull up to read. Slide up or down for more. Release to hide.","Zum Lesen hochziehen. Für mehr hoch- oder runterstreichen. Loslassen verdeckt alles."}},
            {"kingsTableTitle", new[]{"Play around the table.","Spielt am Tisch."}},
            {"kingsTableInstructions", new[]{"Give clues, discuss and vote together. Keep your leader safe.","Gebt Hinweise, diskutiert und stimmt gemeinsam ab. Schützt euren Anführer."}},
            {"kingsHelpTitle", new[]{"Kings rules","Könige: die Regeln"}},
            {"kingsRulesTeamsTitle", new[]{"Two teams, two Kings","Zwei Teams, zwei Könige"}},
            {"kingsRulesTeams", new[]{"5–20 people play. Protect your King and find the opposing King. The good team is the Civilians, including one good King. The evil team is ordinary Undercover plus Mr. White, its King. Each King has teammates; the good team starts larger. The Undercover setting counts ordinary Undercover only; White is additional. Roles are random each match and may repeat. Word selection also remembers earlier matches in other modes.","5–20 Personen spielen. Schützt euren König und findet den gegnerischen. Das gute Team sind die Bürger mit einem guten König. Das böse Team besteht aus gewöhnlichen Undercover und seinem König Mr. White. Beide Könige haben Mitspieler; das gute Team startet in der Mehrheit. Die Undercover-Einstellung zählt nur gewöhnliche Undercover; White kommt dazu. Rollen werden jede Partie zufällig verteilt und können sich wiederholen. Die Wortauswahl berücksichtigt auch vorherige Partien anderer Modi."}},
            {"kingsRulesCardsTitle", new[]{"What your card tells you","Was deine Karte verrät"}},
            {"kingsRulesCards", new[]{"Ordinary players see their word and their leader, but not their side. Civilians share the good word; Undercover share a related alternative. The good King sees the good word and every evil name, without knowing which is their King. Mr. White knows he is the evil King and sees his ordinary teammates. He knows neither word nor the good King and must bluff.","Gewöhnliche Spieler sehen ihr Wort und ihren Anführer, aber nicht ihre Seite. Bürger teilen das gute Wort; Undercover ein verwandtes anderes. Der gute König sieht das gute Wort und alle bösen Namen, ohne deren König zu erkennen. Mr. White kennt seine Rolle als böser König und seine gewöhnlichen Mitspieler. Er kennt weder ein Wort noch den guten König und muss bluffen."}},
            {"kingsRulesPrivacyTitle", new[]{"Read privately, remember","Privat lesen und merken"}},
            {"kingsRulesPrivacy", new[]{"Read only your own initial card. Pull up or hold to reveal; slide up or down for more. Release to hide everything. You may reopen your unfinished handoff, including after an interruption. Once you pass on, there is no review. There is no viewing timer: anyone may look longer as a bluff. Never show your card to others.","Lies nur deine eigene anfängliche Karte. Hochziehen oder gedrückt halten deckt sie auf; hoch- oder runterstreichen zeigt mehr. Loslassen verdeckt alles. Deine noch nicht abgeschlossene Übergabe darfst du erneut öffnen, auch nach einer Unterbrechung. Nach dem Weitergeben gibt es keine Rückschau. Es gibt keine Zeitbegrenzung: Jeder darf zum Bluffen länger schauen. Zeige anderen niemals deine Karte."}},
            {"kingsRulesRoundTitle", new[]{"One clue each, then discuss","Je ein Hinweis, dann diskutieren"}},
            {"kingsRulesRound", new[]{"At the table, randomly choose a surviving starter each clue round, including Mr. White. Continue around the table: every survivor gives one single-word clue, then everyone discusses. Eliminated people give no more clues and cannot vote. The app only records the person actually eliminated; it does not run the discussion, votes or ties.","Lost am Tisch für jede Hinweisrunde einen noch beteiligten Startspieler aus – auch Mr. White kann beginnen. Dann geht es reihum: Jede noch beteiligte Person gibt einen Hinweis aus genau einem Wort, danach diskutiert ihr. Ausgeschiedene geben keine Hinweise mehr und stimmen nicht ab. Die App erfasst nur, wer tatsächlich ausscheidet; Diskussion, Abstimmung und Gleichstand regelt ihr am Tisch."}},
            {"kingsRulesCluesTitle", new[]{"Clues and bluffs","Hinweise und Bluffs"}},
            {"kingsRulesClues", new[]{"Do not use your own secret word, obvious forms or direct translations of it, or spelling and first-letter hints. Saying your own word directly stays forbidden during discussion. Identity and leader claims may be true or false. Naming your real leader is allowed, but risks exposing them; showing the card is forbidden.","Verwendet nicht euer eigenes geheimes Wort, offensichtliche Wortformen, direkte Übersetzungen oder Hinweise auf Schreibweise und Anfangsbuchstaben. Das eigene Wort direkt zu nennen bleibt auch in der Diskussion verboten. Aussagen über Identitäten und Anführer dürfen wahr oder gelogen sein. Den echten Anführer zu nennen ist erlaubt, aber riskant; die Karte zu zeigen ist verboten."}},
            {"kingsRulesVoteTitle", new[]{"Point, then resolve ties","Zeigen und Gleichstand lösen"}},
            {"kingsRulesVote", new[]{"All survivors point simultaneously at another survivor: one vote each. The highest count wins; an absolute majority is unnecessary. A tie gets one spoken runoff among those tied for the highest count. Another tie starts a new clue round without elimination or any app action. Otherwise select the eliminated person in the app. Correct a mistaken selection before confirming.","Alle noch Beteiligten zeigen gleichzeitig auf eine andere noch beteiligte Person: je eine Stimme. Die meisten Stimmen entscheiden, eine absolute Mehrheit ist nicht nötig. Bei Gleichstand gibt es eine mündliche Stichwahl zwischen den Personen mit den meisten Stimmen. Erneuter Gleichstand startet eine neue Hinweisrunde ohne Ausscheiden und ohne App-Aktion. Sonst wählt ihr die ausgeschiedene Person in der App; eine falsche Auswahl könnt ihr vor dem Bestätigen ändern."}},
            {"kingsRulesEliminationTitle", new[]{"Find a King","Einen König finden"}},
            {"kingsRulesElimination", new[]{"An ordinary elimination reveals only “Not a king”. Side, word and leader stay secret. Play continues even at equal team sizes or with just one good survivor. Eliminating the good King wins for the evil team. If only the two Kings remain, evil wins automatically. Eliminating Mr. White first opens his last chance, before the final reveal.","Beim Ausscheiden gewöhnlicher Spieler erscheint nur „Kein König“. Seite, Wort und Anführer bleiben geheim. Auch bei gleich großen Teams oder nur einem verbliebenen Guten geht es weiter. Scheidet der gute König aus, gewinnt das böse Team. Bleiben nur die zwei Könige, gewinnt automatisch das böse Team. Scheidet Mr. White aus, erhält er vor der Schlussaufdeckung seine Letzte Chance."}},
            {"kingsRulesLastChanceTitle", new[]{"White's last chance","Whites Letzte Chance"}},
            {"kingsRulesLastChance", new[]{"Mr. White chooses alone, without anyone's advice: guess the good word OR identify the good King. The choice is binding, with one attempt and no switching or retry. For the word, say one answer aloud, then confirm it was spoken before revealing the target for judgment. For the King, select one survivor and confirm; a pending selection can still be corrected. Restarting the app does not undo committed choices.","Mr. White entscheidet allein, ohne Rat von anderen: das gute Wort raten ODER den guten König finden. Die Wahl ist bindend: ein Versuch, kein Wechsel und kein Wiederholen. Beim Wort nennt er eine Antwort laut. Bestätigt erst danach, dass sie gesprochen wurde; dann erscheint das Zielwort zur Bewertung. Beim König wählt und bestätigt er eine noch beteiligte Person; vor dem Bestätigen lässt sich die Auswahl korrigieren. Ein App-Neustart hebt bestätigte Entscheidungen nicht auf."}},
            {"kingsRulesJudgmentTitle", new[]{"Judge meaning, win together","Bedeutung werten, gemeinsam gewinnen"}},
            {"kingsRulesJudgment", new[]{"The group judges the spoken word by meaning: articles, singular/plural and true synonyms can count; merely related words do not. The app does not listen or compare text. A correct word or King wins for the whole evil team; failure wins for the whole good team, including eliminated teammates. White never wins alone in Kings. Only then are both words, teams and Kings revealed.","Die Gruppe bewertet die Bedeutung der gesprochenen Antwort: Artikel, Einzahl/Mehrzahl und echte Synonyme können gelten; nur verwandte Wörter nicht. Die App hört nicht zu und vergleicht keinen Text. Ein richtiges Wort oder der richtige König gewinnt für das ganze böse Team; ein Fehlversuch für das ganze gute Team, jeweils einschließlich Ausgeschiedener. In Könige gewinnt White nie allein. Erst danach werden beide Wörter, Teams und Könige aufgedeckt."}},
            {"kingsRulesAccidentsTitle", new[]{"Accidents and the next match","Missgeschicke und nächste Partie"}},
            {"kingsRulesAccidents", new[]{"An invalid clue or accidental word leak causes no automatic penalty. Usually continue, or agree to abandon and restart a spoiled match. Back lets you pause or deliberately abandon while keeping the group. A rematch brings back every active group member with fresh assignments.","Ein ungültiger Hinweis oder versehentlich verratenes Wort führt zu keiner automatischen Strafe. Spielt normalerweise weiter oder brecht eine verdorbene Partie gemeinsam ab und startet neu. Über Zurück könnt ihr pausieren oder bewusst abbrechen; die Gruppe bleibt erhalten. Eine Folgepartie bringt alle aktiven Gruppenmitglieder mit neuer Verteilung zurück."}},
            {"appInfo", new[]{"Rules, about, privacy and licenses","Regeln, Info, Datenschutz und Lizenzen"}},
            {"privacyTitle", new[]{"Your game stays here","Euer Spiel bleibt hier"}},
            {"privacyText", new[]{"Word Deduction works offline. No account, ads, purchases or analytics. The app does not send your names or games to us.\n\nNames, participation, settings, the current match and used word pairs stay on this phone in private app storage. Android backups and device transfer are disabled for these files.\n\nPrevious recovery copies can still contain a removed name. To delete all local data, use Android Settings → Apps → Word Deduction → Storage → Clear storage, or uninstall the app.","Word Deduction funktioniert offline. Ohne Konto, Werbung, Käufe oder Analyse. Die App sendet eure Namen und Partien nicht an uns.\n\nNamen, Teilnahme, Einstellungen, die aktuelle Partie und verwendete Wortpaare bleiben auf diesem Handy im privaten App-Speicher. Android-Backups und Geräteübertragung sind für diese Dateien deaktiviert.\n\nÄltere Wiederherstellungskopien können entfernte Namen noch enthalten. Alle lokalen Daten lassen sich unter Android-Einstellungen → Apps → Word Deduction → Speicher → Daten löschen oder durch Deinstallation entfernen."}},
            {"licenses", new[]{"Credits and licenses","Mitwirkende und Lizenzen"}},
            {"licenseIntro", new[]{"Made with Unity. Typography: Inter and Noto Color Emoji. Unicode data: Unicode, Inc. JSON: Newtonsoft.Json. License texts follow in their original language.","Erstellt mit Unity. Schriften: Inter und Noto Color Emoji. Unicode-Daten: Unicode, Inc. JSON: Newtonsoft.Json. Die Lizenztexte folgen in ihrer Originalsprache."}},
            {"scrollPlayers", new[]{"Saved players. Scroll for more.","Gespeicherte Personen. Für weitere scrollen."}},
            {"scrollContent", new[]{"More information. Scroll to continue reading.","Weitere Informationen. Zum Weiterlesen scrollen."}},
            {"privateCardAccessibility", new[]{"Private card. Words are never spoken. To read it visually, use TalkBack's pass-through gesture, then hold here. Release to hide.","Private Karte. Wörter werden nie vorgelesen. Zum visuellen Lesen TalkBack kurz durchreichen lassen und dieses Feld halten. Loslassen verdeckt die Karte."}},
            {"pausePlayer", new[]{"Pause {0}","{0} pausieren"}},
            {"joinPlayer", new[]{"Let {0} join","{0} mitspielen lassen"}},
            {"back", new[]{"Back","Zurück"}},
            {"help", new[]{"Help","Hilfe"}},
            {"ModeUnavailable", new[]{"Classic is being prepared. Choose Quick to play.","Klassisch wird vorbereitet. Wähle Schnell zum Spielen."}},
            {"NotEnoughPlayers", new[]{"More active players are needed for this mode.","Für diesen Modus müssen mehr Personen mitspielen."}},
            {"MatchInProgress", new[]{"Finish or abandon this match before changing the group.","Beendet diese Partie oder brecht sie ab, bevor ihr die Gruppe ändert."}},
            {"InvalidAction", new[]{"That action is no longer available. Continue from this screen.","Diese Aktion ist nicht mehr verfügbar. Macht auf diesem Bildschirm weiter."}},
            {"ReadCardFirst", new[]{"Read your word, then release the card before continuing.","Lies dein Wort und lass die Karte los, bevor es weitergeht."}},
            {"cardProgress", new[]{"CARD {0} OF {1}","KARTE {0} VON {1}"}},
            {"handoffHint", new[]{"Pass the phone to this person.","Gib dieser Person das Handy."}},
            {"cardPrivate", new[]{"For your eyes only","Nur für dich"}},
            {"dragHint", new[]{"Pull up your card. Release to hide it.","Karte hochziehen. Loslassen verdeckt sie."}},
            {"groupCapacity", new[]{"40 names saved. Group full.","40 Namen gespeichert. Voll."}},
            {"holdReveal", new[]{"Hold to read","Gedrückt halten"}},
            {"whitePrivate", new[]{"Mr. White\nYou have no word.\nBluff with a clue.","Mr. White\nDu hast kein Wort.\nBluffe mit einem Hinweis."}},
            {"nextOwner", new[]{"Hide & pass on","Handy weitergeben"}},
            {"beginClues", new[]{"Everyone is ready","Alle sind bereit"}},
            {"clueTitle", new[]{"Time for clues.","Zeit für Hinweise."}},
            {"clueInstructions", new[]{"Put the phone down. In order, everyone gives one short clue about their word. Don't say the word itself.","Legt das Handy ab. Reihum gibt jede Person einen kurzen Hinweis zum eigenen Wort. Sagt das Wort selbst nicht."}},
            {"starts", new[]{"STARTS THE CLUE ROUND","BEGINNT DIE HINWEISRUNDE"}},
            {"clueDiscussion", new[]{"Then discuss: who might have a different word? You get one vote together.","Diskutiert danach: Wer könnte ein anderes Wort haben? Ihr stimmt einmal gemeinsam ab."}},
            {"beginVote", new[]{"Ready to vote","Bereit zum Abstimmen"}},
            {"voteTitle", new[]{"Who is your suspect?","Wen verdächtigt ihr?"}},
            {"voteInstructions", new[]{"Vote aloud or point at the same time. Select the person with the most votes.","Stimmt laut ab oder zeigt gleichzeitig auf jemanden. Wählt die Person mit den meisten Stimmen."}},
            {"runoffTitle", new[]{"One short runoff.","Eine kurze Stichwahl."}},
            {"runoffInstructions", new[]{"Discuss briefly, then vote again among the tied people. Select the winner. Another tie lets Undercover escape.","Diskutiert kurz und stimmt erneut zwischen den Personen mit Gleichstand ab. Wählt das Ergebnis. Bei erneutem Gleichstand entkommt Undercover."}},
            {"firstTie", new[]{"It's a tie — runoff","Gleichstand · Stichwahl"}},
            {"secondTie", new[]{"Still tied — show result","Wieder Gleichstand · Ergebnis"}},
            {"confirmTitle", new[]{"Confirm your suspect.","Verdacht bestätigen."}},
            {"confirmHint", new[]{"The result reveals everyone's role. You can still change this selection.","Das Ergebnis zeigt alle Rollen. Ihr könnt diese Auswahl noch ändern."}},
            {"confirmSuspect", new[]{"Confirm & reveal result","Bestätigen & Ergebnis zeigen"}},
            {"changeSuspect", new[]{"Choose someone else","Andere Person wählen"}},
            {"civilianWin", new[]{"Civilians win!","Die Bürger gewinnen!"}},
            {"undercoverWin", new[]{"Undercover wins!","Undercover gewinnt!"}},
            {"whiteWin", new[]{"Mr. White wins!","Mr. White gewinnt!"}},
            {"adversariesWin", new[]{"Undercover & Mr. White win!","Undercover & Mr. White gewinnen!"}},
            {"White", new[]{"Mr. White","Mr. White"}},
            {"AllAdversariesEliminated", new[]{"All Undercover players and Mr. White are out.","Alle Undercover und Mr. White sind ausgeschieden."}},
            {"OneCivilianRemains", new[]{"Only one Civilian is left. The outsiders still in the match win.","Nur ein Bürger ist übrig. Die übrigen Gegenspieler gewinnen."}},
            {"WhiteGuessed", new[]{"Mr. White guessed the Civilian word correctly and wins alone.","Mr. White hat das Bürgerwort richtig erraten und gewinnt allein."}},
            {"classicClueTitle", new[]{"Clue round {0}.","Hinweisrunde {0}."}},
            {"classicClueInstructions", new[]{"{0} people remain. Everyone still in gives one short clue, in order. Keep your word secret.","{0} Personen sind noch dabei. Wer noch dabei ist, gibt reihum einen kurzen Hinweis. Haltet euer Wort geheim."}},
            {"classicDiscussion", new[]{"Then discuss and vote aloud: who should be eliminated?","Diskutiert danach und stimmt laut ab: Wer soll ausscheiden?"}},
            {"classicConfirmHint", new[]{"This eliminates the selected person and reveals their role. You can still change your selection now.","Die gewählte Person scheidet aus und ihre Rolle wird aufgedeckt. Jetzt könnt ihr die Auswahl noch ändern."}},
            {"confirmElimination", new[]{"Confirm elimination","Ausscheiden bestätigen"}},
            {"classicRunoffInstructions", new[]{"Discuss briefly, then vote again among the tied people. If still tied, everyone survives to the next clue round.","Diskutiert kurz und stimmt erneut zwischen den Personen mit Gleichstand ab. Bei erneutem Gleichstand bleiben alle in der nächsten Hinweisrunde dabei."}},
            {"classicSecondTie", new[]{"Still tied · next clue round","Wieder Gleichstand · nächste Runde"}},
            {"eliminationTitle", new[]{"Role revealed.","Rolle aufgedeckt."}},
            {"eliminationText", new[]{"This person is out of this match. Their word stays secret. {0} people play on.","Diese Person ist für diese Partie ausgeschieden. Ihr Wort bleibt geheim. {0} Personen spielen weiter."}},
            {"continueRound", new[]{"Next clue round","Nächste Hinweisrunde"}},
            {"whiteGuessTitle", new[]{"Mr. White: one guess.","Mr. White: ein Versuch."}},
            {"whiteGuessText", new[]{"You are out. Say your guess for the Civilian word aloud.\n\nEveryone judges the meaning together: is it correct? The word stays hidden until the final result.","Du bist ausgeschieden. Rate laut das Wort der Bürger.\n\nDie Gruppe bewertet gemeinsam die Bedeutung: Stimmt der Tipp? Das Wort bleibt bis zum Ergebnis verborgen."}},
            {"whiteCorrect", new[]{"Correct · Mr. White wins","Richtig · Mr. White gewinnt"}},
            {"whiteIncorrect", new[]{"Incorrect","Falsch"}},
            {"classicHelpTitle", new[]{"Classic, round by round.","Klassisch, Runde für Runde."}},
            {"classicHelpText", new[]{"1. Read your private card, then release to hide it. Civilians share one word; Undercover has a related word. Neither knows their role yet. Optional Mr. White has no word and must bluff.\n\n2. Everyone still in gives one clue. The starting person is chosen randomly each round. Mr. White can start too, and may need to improvise without prior clues.\n\n3. Discuss and vote aloud. Select the person with the most votes and confirm to eliminate them. Their role is shown; their word stays hidden. A tie gets one runoff among the tied people. A second tie starts a new clue round without elimination.\n\n4. An eliminated Mr. White gets one spoken guess at the Civilian word. Judge its meaning together. Correct means Mr. White wins alone. Incorrect means White is out and play continues, unless the match is over.\n\n5. Civilians win when every adversary is out. With only one Civilian left, surviving Undercover and/or Mr. White win.\n\nBack pauses the match. The next match includes everyone active in your saved group.","1. Lest eure private Karte und lasst sie zum Verdecken los. Bürger teilen ein Wort; Undercover hat ein verwandtes Wort. Beide kennen ihre Rolle noch nicht. Der optionale Mr. White hat kein Wort und muss bluffen.\n\n2. Wer noch dabei ist, gibt einen Hinweis. Wer beginnt, wird jede Runde ausgelost. Auch Mr. White kann anfangen und muss dann ohne vorherige Hinweise improvisieren.\n\n3. Diskutiert und stimmt laut ab. Wählt die Person mit den meisten Stimmen und bestätigt ihr Ausscheiden. Ihre Rolle wird gezeigt; ihr Wort bleibt geheim. Bei Gleichstand gibt es eine Stichwahl zwischen den betroffenen Personen. Erneuter Gleichstand startet eine Hinweisrunde ohne Ausscheiden.\n\n4. Ein ausgeschiedener Mr. White darf einmal laut das Bürgerwort raten. Bewertet gemeinsam die Bedeutung. Richtig heißt: Mr. White gewinnt allein. Falsch heißt: White ist raus und ihr spielt weiter, falls die Partie nicht beendet ist.\n\n5. Bürger gewinnen, wenn alle Gegenspieler ausgeschieden sind. Bleibt nur ein Bürger, gewinnen die übrigen Undercover und/oder Mr. White.\n\nZurück pausiert die Partie. In der nächsten Partie sind alle aktiven Gruppenmitglieder wieder dabei."}},
            {"CaughtUndercover", new[]{"You found the person with the different word.","Ihr habt die Person mit dem anderen Wort gefunden."}},
            {"AccusedCivilian", new[]{"You accused a Civilian. Undercover slipped away.","Ihr habt einen Bürger verdächtigt. Undercover ist entkommen."}},
            {"RepeatedTie", new[]{"The runoff was tied too. Undercover escapes.","Auch die Stichwahl endete im Gleichstand. Undercover entkommt."}},
            {"Civilian", new[]{"Civilian","Bürger"}},
            {"Undercover", new[]{"Undercover","Undercover"}},
            {"rolesTitle", new[]{"EVERYONE'S ROLE","ALLE ROLLEN"}},
            {"rematch", new[]{"Next match","Nächste Partie"}},
            {"editGroup", new[]{"Edit group","Gruppe bearbeiten"}},
            {"pauseTitle", new[]{"Your match is safe.","Eure Partie ist gesichert."}},
            {"pauseText", new[]{"Same people. Same words. Continue when you're ready — cards always resume covered.","Gleiche Personen. Gleiche Wörter. Spielt weiter, wenn ihr bereit seid. Karten bleiben zunächst verdeckt."}},
            {"resumeMatch", new[]{"Resume match","Partie fortsetzen"}},
            {"abandonMatch", new[]{"Abandon match","Partie abbrechen"}},
            {"abandonTitle", new[]{"End this match?","Diese Partie beenden?"}},
            {"abandonText", new[]{"This deal will end without a result. Your saved group stays ready for the next match.","Diese Partie endet ohne Ergebnis. Eure gespeicherte Gruppe bleibt für die nächste Partie erhalten."}},
            {"keepMatch", new[]{"Keep this match","Partie behalten"}},
            {"confirmAbandon", new[]{"Yes, abandon match","Ja, Partie abbrechen"}},
            {"helpTitle", new[]{"Quick, together.","Schnell, gemeinsam."}},
            {"helpText", new[]{"1. Pass the phone. Pull up your card or hold the alternative area. Release to hide it. You see only your word; you don't know your role yet.\n\n2. Everyone gives one clue. Exactly one person has a related but different word: Undercover. All others are Civilians.\n\n3. Discuss and vote aloud. Select the most-voted person and confirm. Find Undercover to win as Civilians; a wrong accusation lets Undercover win.\n\n4. A tie gets one short runoff among the tied people. If still tied, Undercover escapes.\n\nNeed a break? Back covers the card and pauses the match.","1. Gebt das Handy weiter. Zieht eure Karte hoch oder haltet das alternative Feld. Loslassen verdeckt sie. Ihr seht nur euer Wort und kennt eure Rolle noch nicht.\n\n2. Jede Person gibt einen Hinweis. Genau eine Person hat ein verwandtes, aber anderes Wort: Undercover. Alle anderen sind Bürger.\n\n3. Diskutiert und stimmt laut ab. Wählt die Person mit den meisten Stimmen und bestätigt. Findet Undercover, um als Bürger zu gewinnen. Ein falscher Verdacht lässt Undercover gewinnen.\n\n4. Bei Gleichstand gibt es eine kurze Stichwahl zwischen den betroffenen Personen. Bleibt es dabei, entkommt Undercover.\n\nBraucht ihr eine Pause? Zurück verdeckt die Karte und pausiert die Partie."}},
            {"closeHelp", new[]{"Got it","Verstanden"}},
            {"title", new[]{"Good company.\nHidden words.","Gute Runde.\nGeheime Wörter."}},
            {"subtitle", new[]{"One phone. Everyone is in on it.","Ein Handy. Alle sind dabei."}},
            {"group", new[]{"Your group","Eure Gruppe"}},
            {"count", new[]{"{0} playing","{0} spielen mit"}},
            {"countOne", new[]{"1 playing","1 spielt mit"}},
            {"emptyTitle", new[]{"Who's joining?","Wer ist dabei?"}},
            {"emptyHint", new[]{"Add your first player.","Ersten Namen eingeben."}},
            {"name", new[]{"Player name","Name eingeben"}},
            {"add", new[]{"Add player","Person hinzufügen"}},
            {"editHint", new[]{"Tap a name to edit it.","Namen antippen zum Ändern."}},
            {"pause", new[]{"Pause","Pause"}}, {"join", new[]{"Join","Mitspielen"}},
            {"edit", new[]{"Edit {0}","{0} bearbeiten"}}, {"save", new[]{"Save","Speichern"}},
            {"cancel", new[]{"Cancel","Abbrechen"}}, {"remove", new[]{"Remove","Entfernen"}},
            {"quick", new[]{"Quick","Schnell"}}, {"classic", new[]{"Classic","Klassisch"}},
            {"quickDescription", new[]{"One clue round. One vote. Everyone stays in.","Eine Hinweisrunde. Eine Abstimmung. Alle bleiben dabei."}},
            {"classicDescription", new[]{"Find the outsiders, one elimination at a time.","Entlarvt die anderen – Runde für Runde."}},
            {"roleMix", new[]{"{0} Civilians · {1} Undercover · {2} Mr. White","{0} Bürger · {1} Undercover · {2} Mr. White"}},
            {"whiteOff", new[]{"Mr. White: off","Mr. White: aus"}},
            {"whiteOn", new[]{"Mr. White: on","Mr. White: an"}},
            {"whiteUnavailable", new[]{"Mr. White · from 5 players","Mr. White · ab 5 Personen"}},
            {"whiteSavedUnavailable", new[]{"Mr. White on · from 5 players","Mr. White an · ab 5 Personen"}},
            {"play", new[]{"Let's play","Los geht's"}},
            {"needed", new[]{"{0} more players needed.","Noch {0} Personen."}},
            {"neededOne", new[]{"Add one more player.","Noch eine Person."}},
            {"ready", new[]{"Your group is saved. Ready when you are.","Eure Gruppe ist gespeichert. Ihr könnt loslegen."}},
            {"undo", new[]{"Undo removal","Entfernen rückgängig"}},
            {"Removed", new[]{"Player removed.","Person entfernt."}},
            {"InvalidName", new[]{"Use 1–24 characters, without line breaks.","Bitte 1–24 Zeichen ohne Zeilenumbrüche verwenden."}},
            {"GroupFull", new[]{"40 names are saved. Remove someone to add another.","40 Namen sind gespeichert. Entferne jemanden, um weitere hinzuzufügen."}},
            {"ActiveFull", new[]{"20 people are playing. Pause someone first.","20 Personen spielen mit. Pausiere zuerst jemanden."}},
            {"AddedPaused", new[]{"Saved and paused: 20 people are already playing.","Gespeichert und pausiert: 20 Personen spielen bereits mit."}},
            {"SaveFailed", new[]{"Couldn't save this action. Nothing changed. Try again. If it keeps happening, check your phone's free storage.","Speichern nicht möglich. Nichts wurde geändert. Versuche es erneut. Falls es weiter passiert, prüfe den freien Speicherplatz."}},
            {"NothingToUndo", new[]{"There is no removal to undo.","Es gibt nichts rückgängig zu machen."}},
            {"PlayerNotFound", new[]{"That player is no longer in the group.","Diese Person ist nicht mehr in der Gruppe."}},
            {"InvalidSetting", new[]{"That setting isn't available.","Diese Einstellung ist nicht verfügbar."}},
            {"StorageBlocked", new[]{"Your saved group needs attention before you can continue.","Bitte prüfe den Speicherhinweis, bevor es weitergeht."}},
            {"RecoveredBackup", new[]{"The latest save was damaged. The previous saved state was restored. Please check where you left off.","Der letzte Speicherstand war beschädigt. Der vorherige Stand wurde wiederhergestellt. Prüft bitte euren Fortschritt."}},
            {"DamagedData", new[]{"The saved group couldn't be recovered. Keep the damaged files and start a new group?", "Die gespeicherte Gruppe konnte nicht wiederhergestellt werden. Beschädigte Dateien behalten und eine neue Gruppe anfangen?"}},
            {"NewerVersion", new[]{"This save comes from a newer app version. Update the app to keep playing. Your files are untouched.","Dieser Speicherstand stammt aus einer neueren App-Version. Aktualisiere die App zum Weiterspielen. Die Dateien bleiben erhalten."}},
            {"ReadFailed", new[]{"Your saved group isn't accessible. Close and reopen the app to retry. Your files are untouched.","Auf die gespeicherte Gruppe kann nicht zugegriffen werden. Schließe und öffne die App erneut. Die Dateien bleiben erhalten."}},
            {"startFresh", new[]{"Keep files & start fresh","Dateien behalten & neu anfangen"}},
            {"english", new[]{"English","Englisch"}}, {"german", new[]{"German","Deutsch"}}
        };
        public static string Get(Language language, string key, params object[] arguments)
        {
            if (!Text.TryGetValue(key, out var values)) throw new ArgumentException("Missing UI copy: " + key);
            return string.Format(language == Language.German ? CultureInfo.GetCultureInfo("de-DE") : CultureInfo.GetCultureInfo("en-US"), values[language == Language.German ? 1 : 0], arguments);
        }
    }
}
