// Generated from content/word-pairs.json by content/compile-catalog.cjs. Preserve stable IDs.
namespace WordDeduction
{
    internal static class WordCatalog
    {
        internal sealed class Pair
        {
            public readonly string Id;
            public readonly string[] German, English;
            public Pair(string id, string deA, string deB, string enA, string enB) { Id=id; German=new[]{deA,deB}; English=new[]{enA,enB}; }
        }
        internal static readonly Pair[] Pairs = {
            new Pair("fruit-vegetables-001", "Apfel", "Birne", "Apple", "Pear"),
            new Pair("fruit-vegetables-002", "Pfirsich", "Aprikose", "Peach", "Apricot"),
            new Pair("fruit-vegetables-003", "Pflaume", "Kirsche", "Plum", "Cherry"),
            new Pair("fruit-vegetables-004", "Erdbeere", "Himbeere", "Strawberry", "Raspberry"),
            new Pair("fruit-vegetables-005", "Blaubeere", "Brombeere", "Blueberry", "Blackberry"),
            new Pair("fruit-vegetables-006", "Zitrone", "Limette", "Lemon", "Lime"),
            new Pair("fruit-vegetables-007", "Orange", "Mandarine", "Orange", "Mandarin"),
            new Pair("fruit-vegetables-008", "Ananas", "Melone", "Pineapple", "Melon"),
            new Pair("fruit-vegetables-009", "Banane", "Mango", "Banana", "Mango"),
            new Pair("fruit-vegetables-010", "Kiwi", "Passionsfrucht", "Kiwi", "Passion fruit"),
            new Pair("fruit-vegetables-011", "Wassermelone", "Honigmelone", "Watermelon", "Honeydew melon"),
            new Pair("fruit-vegetables-012", "Traube", "Rote Johannisbeere", "Grape", "Redcurrant"),
            new Pair("fruit-vegetables-013", "Feige", "Dattel", "Fig", "Date"),
            new Pair("fruit-vegetables-014", "Kokosnuss", "Avocado", "Coconut", "Avocado"),
            new Pair("fruit-vegetables-015", "Rosine", "Trockenpflaume", "Raisin", "Prune"),
            new Pair("fruit-vegetables-016", "Karotte", "Radieschen", "Carrot", "Radish"),
            new Pair("fruit-vegetables-017", "Kartoffel", "Süßkartoffel", "Potato", "Sweet potato"),
            new Pair("fruit-vegetables-018", "Tomate", "Paprika", "Tomato", "Bell pepper"),
            new Pair("fruit-vegetables-019", "Gurke", "Zucchini", "Cucumber", "Courgette"),
            new Pair("fruit-vegetables-020", "Brokkoli", "Blumenkohl", "Broccoli", "Cauliflower"),
            new Pair("fruit-vegetables-021", "Zwiebel", "Knoblauch", "Onion", "Garlic"),
            new Pair("fruit-vegetables-022", "Erbse", "Bohne", "Pea", "Bean"),
            new Pair("fruit-vegetables-023", "Lauch", "Frühlingszwiebel", "Leek", "Spring onion"),
            new Pair("fruit-vegetables-024", "Rotkohl", "Weißkohl", "Red cabbage", "White cabbage"),
            new Pair("fruit-vegetables-025", "Kürbis", "Aubergine", "Pumpkin", "Aubergine"),
            new Pair("fruit-vegetables-026", "Mais", "Spargel", "Sweetcorn", "Asparagus"),
            new Pair("meals-001", "Pizza", "Quiche", "Pizza", "Quiche"),
            new Pair("meals-002", "Hamburger", "Hotdog", "Hamburger", "Hot dog"),
            new Pair("meals-003", "Sandwich", "Wrap", "Sandwich", "Wrap"),
            new Pair("meals-004", "Spaghetti", "Lasagne", "Spaghetti", "Lasagne"),
            new Pair("meals-005", "Reis", "Couscous", "Rice", "Couscous"),
            new Pair("meals-006", "Pommes", "Kroketten", "Chips", "Croquettes"),
            new Pair("meals-007", "Kartoffelpüree", "Kartoffelsalat", "Mashed potatoes", "Potato salad"),
            new Pair("meals-008", "Suppe", "Eintopf", "Soup", "Stew"),
            new Pair("meals-009", "Rührei", "Spiegelei", "Scrambled egg", "Fried egg"),
            new Pair("meals-010", "Omelett", "Pfannkuchen", "Omelette", "Pancake"),
            new Pair("meals-011", "Sushi", "Frühlingsrolle", "Sushi", "Spring roll"),
            new Pair("meals-012", "Döner", "Falafel", "Doner kebab", "Falafel"),
            new Pair("meals-013", "Taco", "Burrito", "Taco", "Burrito"),
            new Pair("meals-014", "Schnitzel", "Bratwurst", "Breaded cutlet", "Grilled sausage"),
            new Pair("meals-015", "Steak", "Kotelett", "Steak", "Chop"),
            new Pair("meals-016", "Hähnchenflügel", "Hähnchenschenkel", "Chicken wing", "Chicken leg"),
            new Pair("meals-017", "Fischstäbchen", "Hähnchennugget", "Fish finger", "Chicken nugget"),
            new Pair("meals-018", "Ravioli", "Tortellini", "Ravioli", "Tortellini"),
            new Pair("meals-019", "Nudel", "Kloß", "Noodle", "Dumpling"),
            new Pair("meals-020", "Risotto", "Paella", "Risotto", "Paella"),
            new Pair("meals-021", "Gemüsespieß", "Fleischspieß", "Vegetable skewer", "Meat skewer"),
            new Pair("meals-022", "Nudelauflauf", "Kartoffelgratin", "Pasta bake", "Potato gratin"),
            new Pair("meals-023", "Linsensuppe", "Tomatensuppe", "Lentil soup", "Tomato soup"),
            new Pair("meals-024", "Caesarsalat", "Griechischer Salat", "Caesar salad", "Greek salad"),
            new Pair("meals-025", "Toast", "Zwieback", "Toast", "Rusk"),
            new Pair("meals-026", "Müsli", "Haferbrei", "Muesli", "Porridge"),
            new Pair("bakery-sweets-001", "Baguette", "Brötchen", "Baguette", "Bread roll"),
            new Pair("bakery-sweets-002", "Croissant", "Brezel", "Croissant", "Pretzel"),
            new Pair("bakery-sweets-003", "Vollkornbrot", "Weißbrot", "Wholemeal bread", "White bread"),
            new Pair("bakery-sweets-004", "Bagel", "Fladenbrot", "Bagel", "Flatbread"),
            new Pair("bakery-sweets-005", "Keks", "Waffel", "Biscuit", "Waffle"),
            new Pair("bakery-sweets-006", "Muffin", "Cupcake", "Muffin", "Cupcake"),
            new Pair("bakery-sweets-007", "Brownie", "Donut", "Brownie", "Doughnut"),
            new Pair("bakery-sweets-008", "Käsekuchen", "Apfelkuchen", "Cheesecake", "Apple cake"),
            new Pair("bakery-sweets-009", "Schokoladenkuchen", "Zitronenkuchen", "Chocolate cake", "Lemon cake"),
            new Pair("bakery-sweets-010", "Apfelstrudel", "Zimtschnecke", "Apple strudel", "Cinnamon roll"),
            new Pair("bakery-sweets-011", "Lebkuchen", "Baiser", "Gingerbread", "Meringue"),
            new Pair("bakery-sweets-012", "Marzipan", "Krokant", "Marzipan", "Nut brittle"),
            new Pair("bakery-sweets-013", "Schokolade", "Karamell", "Chocolate", "Caramel"),
            new Pair("bakery-sweets-014", "Gummibärchen", "Lakritz", "Gummy bear", "Liquorice"),
            new Pair("bakery-sweets-015", "Bonbon", "Lutscher", "Boiled sweet", "Lollipop"),
            new Pair("bakery-sweets-016", "Kaugummi", "Zuckerwatte", "Chewing gum", "Candyfloss"),
            new Pair("bakery-sweets-017", "Vanilleeis", "Schokoladeneis", "Vanilla ice cream", "Chocolate ice cream"),
            new Pair("bakery-sweets-018", "Eis am Stiel", "Eiswaffel", "Ice lolly", "Ice cream cone"),
            new Pair("bakery-sweets-019", "Sorbet", "Frozen Yogurt", "Sorbet", "Frozen yoghurt"),
            new Pair("bakery-sweets-020", "Vanillepudding", "Wackelpudding", "Vanilla pudding", "Jelly"),
            new Pair("bakery-sweets-021", "Milchreis", "Grießbrei", "Rice pudding", "Semolina pudding"),
            new Pair("bakery-sweets-022", "Obstsalat", "Fruchtjoghurt", "Fruit salad", "Fruit yoghurt"),
            new Pair("bakery-sweets-023", "Honig", "Marmelade", "Honey", "Jam"),
            new Pair("bakery-sweets-024", "Erdnussbutter", "Nuss-Nougat-Creme", "Peanut butter", "Chocolate hazelnut spread"),
            new Pair("bakery-sweets-025", "Popcorn", "Kartoffelchips", "Popcorn", "Crisps"),
            new Pair("bakery-sweets-026", "Salzstange", "Cracker", "Pretzel stick", "Cracker"),
            new Pair("drinks-pantry-001", "Kaffee", "Tee", "Coffee", "Tea"),
            new Pair("drinks-pantry-002", "Espresso", "Cappuccino", "Espresso", "Cappuccino"),
            new Pair("drinks-pantry-003", "Apfelschorle", "Traubensaft", "Apple juice spritzer", "Grape juice"),
            new Pair("drinks-pantry-004", "Eistee", "Eiskaffee", "Iced tea", "Iced coffee"),
            new Pair("drinks-pantry-005", "Apfelsaft", "Orangensaft", "Apple juice", "Orange juice"),
            new Pair("drinks-pantry-006", "Limonade", "Fruchtpunsch", "Lemonade", "Fruit punch"),
            new Pair("drinks-pantry-007", "Mineralwasser", "Leitungswasser", "Mineral water", "Tap water"),
            new Pair("drinks-pantry-008", "Milchshake", "Smoothie", "Milkshake", "Smoothie"),
            new Pair("drinks-pantry-009", "Frischkäse", "Hüttenkäse", "Cream cheese", "Cottage cheese"),
            new Pair("drinks-pantry-010", "Kokosmilch", "Hafermilch", "Coconut milk", "Oat milk"),
            new Pair("drinks-pantry-011", "Milch", "Sahne", "Milk", "Cream"),
            new Pair("drinks-pantry-012", "Pfefferminztee", "Kamillentee", "Peppermint tea", "Camomile tea"),
            new Pair("drinks-pantry-013", "Schwarzer Tee", "Grüner Tee", "Black tea", "Green tea"),
            new Pair("drinks-pantry-014", "Zucker", "Salz", "Sugar", "Salt"),
            new Pair("drinks-pantry-015", "Mehl", "Speisestärke", "Flour", "Cornflour"),
            new Pair("drinks-pantry-016", "Backpulver", "Hefe", "Baking powder", "Yeast"),
            new Pair("drinks-pantry-017", "Butter", "Margarine", "Butter", "Margarine"),
            new Pair("drinks-pantry-018", "Olivenöl", "Sonnenblumenöl", "Olive oil", "Sunflower oil"),
            new Pair("drinks-pantry-019", "Essig", "Zitronensaft", "Vinegar", "Lemon juice"),
            new Pair("drinks-pantry-020", "Ketchup", "Senf", "Ketchup", "Mustard"),
            new Pair("drinks-pantry-021", "Mayonnaise", "Salatsoße", "Mayonnaise", "Salad dressing"),
            new Pair("drinks-pantry-022", "Pesto", "Tomatensoße", "Pesto", "Tomato sauce"),
            new Pair("drinks-pantry-023", "Zimt", "Vanille", "Cinnamon", "Vanilla"),
            new Pair("drinks-pantry-024", "Pfeffer", "Chilipulver", "Pepper", "Chilli powder"),
            new Pair("drinks-pantry-025", "Walnuss", "Haselnuss", "Walnut", "Hazelnut"),
            new Pair("drinks-pantry-026", "Mandel", "Cashewkern", "Almond", "Cashew nut"),
            new Pair("kitchen-001", "Teller", "Schüssel", "Plate", "Bowl"),
            new Pair("kitchen-002", "Tasse", "Trinkglas", "Cup", "Drinking glass"),
            new Pair("kitchen-003", "Thermoskanne", "Wasserkrug", "Vacuum flask", "Water jug"),
            new Pair("kitchen-004", "Gabel", "Löffel", "Fork", "Spoon"),
            new Pair("kitchen-005", "Küchenmesser", "Schere", "Kitchen knife", "Scissors"),
            new Pair("kitchen-006", "Topf", "Pfanne", "Saucepan", "Frying pan"),
            new Pair("kitchen-007", "Wok", "Bräter", "Wok", "Roasting tin"),
            new Pair("kitchen-008", "Wasserkocher", "Kaffeemaschine", "Kettle", "Coffee machine"),
            new Pair("kitchen-009", "Toaster", "Sandwichtoaster", "Toaster", "Sandwich toaster"),
            new Pair("kitchen-010", "Backofen", "Mikrowelle", "Oven", "Microwave"),
            new Pair("kitchen-011", "Kühlschrank", "Gefrierschrank", "Fridge", "Freezer"),
            new Pair("kitchen-012", "Spülmaschine", "Spülbecken", "Dishwasher", "Kitchen sink"),
            new Pair("kitchen-013", "Schneidebrett", "Backblech", "Chopping board", "Baking tray"),
            new Pair("kitchen-014", "Sieb", "Trichter", "Sieve", "Funnel"),
            new Pair("kitchen-015", "Schneebesen", "Handmixer", "Whisk", "Hand mixer"),
            new Pair("kitchen-016", "Standmixer", "Entsafter", "Blender", "Juicer"),
            new Pair("kitchen-017", "Pfannenwender", "Suppenkelle", "Spatula", "Ladle"),
            new Pair("kitchen-018", "Salatbesteck", "Grillzange", "Salad servers", "Barbecue tongs"),
            new Pair("kitchen-019", "Reibe", "Sparschäler", "Grater", "Vegetable peeler"),
            new Pair("kitchen-020", "Nudelholz", "Kartoffelstampfer", "Rolling pin", "Potato masher"),
            new Pair("kitchen-021", "Dosenöffner", "Korkenzieher", "Tin opener", "Corkscrew"),
            new Pair("kitchen-022", "Küchenwaage", "Messbecher", "Kitchen scales", "Measuring jug"),
            new Pair("kitchen-023", "Brotdose", "Vorratsglas", "Lunch box", "Storage jar"),
            new Pair("kitchen-024", "Alufolie", "Frischhaltefolie", "Kitchen foil", "Cling film"),
            new Pair("kitchen-025", "Serviette", "Küchenpapier", "Napkin", "Kitchen roll"),
            new Pair("kitchen-026", "Geschirrtuch", "Topflappen", "Tea towel", "Pot holder"),
            new Pair("home-001", "Stuhl", "Hocker", "Chair", "Stool"),
            new Pair("home-002", "Sofa", "Sessel", "Sofa", "Armchair"),
            new Pair("home-003", "Bett", "Hängematte", "Bed", "Hammock"),
            new Pair("home-004", "Matratze", "Luftmatratze", "Mattress", "Air mattress"),
            new Pair("home-005", "Kissen", "Decke", "Pillow", "Blanket"),
            new Pair("home-006", "Bettlaken", "Bettbezug", "Bedsheet", "Duvet cover"),
            new Pair("home-007", "Tisch", "Schreibtisch", "Table", "Desk"),
            new Pair("home-008", "Schrank", "Regal", "Cupboard", "Shelving unit"),
            new Pair("home-009", "Kommode", "Nachttisch", "Chest of drawers", "Bedside table"),
            new Pair("home-010", "Kleiderständer", "Garderobenhaken", "Clothes rail", "Coat hook"),
            new Pair("home-011", "Spiegel", "Bilderrahmen", "Mirror", "Picture frame"),
            new Pair("home-012", "Teppich", "Fußmatte", "Carpet", "Doormat"),
            new Pair("home-013", "Vorhang", "Rollo", "Curtain", "Roller blind"),
            new Pair("home-014", "Stehlampe", "Tischlampe", "Floor lamp", "Table lamp"),
            new Pair("home-015", "Kronleuchter", "Lichterkette", "Chandelier", "Fairy lights"),
            new Pair("home-016", "Kamin", "Heizkörper", "Fireplace", "Radiator"),
            new Pair("home-017", "Ventilator", "Klimaanlage", "Fan", "Air conditioner"),
            new Pair("home-018", "Tür", "Fenster", "Door", "Window"),
            new Pair("home-019", "Treppe", "Leiter", "Stairs", "Ladder"),
            new Pair("home-020", "Balkon", "Terrasse", "Balcony", "Patio"),
            new Pair("home-021", "Dachboden", "Keller", "Attic", "Cellar"),
            new Pair("home-022", "Tapete", "Wandfarbe", "Wallpaper", "Wall paint"),
            new Pair("home-023", "Parkett", "Fliesen", "Parquet flooring", "Tiles"),
            new Pair("home-024", "Besen", "Staubsauger", "Broom", "Vacuum cleaner"),
            new Pair("home-025", "Wischmopp", "Bürste", "Mop", "Brush"),
            new Pair("home-026", "Wäschekorb", "Mülltonne", "Laundry basket", "Dustbin"),
            new Pair("clothing-001", "T-Shirt", "Hemd", "T-shirt", "Shirt"),
            new Pair("clothing-002", "Bluse", "Tunika", "Blouse", "Tunic"),
            new Pair("clothing-003", "Pullover", "Strickjacke", "Jumper", "Cardigan"),
            new Pair("clothing-004", "Kapuzenpullover", "Rollkragenpullover", "Hoodie", "Turtleneck jumper"),
            new Pair("clothing-005", "Jeans", "Cordhose", "Jeans", "Corduroy trousers"),
            new Pair("clothing-006", "Shorts", "Badehose", "Shorts", "Swimming trunks"),
            new Pair("clothing-007", "Rock", "Kleid", "Skirt", "Dress"),
            new Pair("clothing-008", "Anzug", "Smoking", "Suit", "Dinner suit"),
            new Pair("clothing-009", "Mantel", "Jacke", "Coat", "Jacket"),
            new Pair("clothing-010", "Regenjacke", "Skijacke", "Raincoat", "Ski jacket"),
            new Pair("clothing-011", "Schal", "Halstuch", "Scarf", "Neckerchief"),
            new Pair("clothing-012", "Strickmütze", "Baseballkappe", "Beanie", "Baseball cap"),
            new Pair("clothing-013", "Handschuh", "Fäustling", "Glove", "Mitten"),
            new Pair("clothing-014", "Socke", "Strumpfhose", "Sock", "Tights"),
            new Pair("clothing-015", "Unterhemd", "Unterhose", "Undershirt", "Underpants"),
            new Pair("clothing-016", "Schlafanzug", "Nachthemd", "Pyjamas", "Nightdress"),
            new Pair("clothing-017", "Bademantel", "Schürze", "Bathrobe", "Apron"),
            new Pair("clothing-018", "Turnschuh", "Wanderschuh", "Trainer", "Hiking boot"),
            new Pair("clothing-019", "Stiefel", "Sandale", "Boot", "Sandal"),
            new Pair("clothing-020", "Hausschuh", "Flipflop", "Slipper", "Flip-flop"),
            new Pair("clothing-021", "Gürtel", "Hosenträger", "Belt", "Braces"),
            new Pair("clothing-022", "Krawatte", "Fliege", "Tie", "Bow tie"),
            new Pair("clothing-023", "Knopf", "Reißverschluss", "Button", "Zip"),
            new Pair("clothing-024", "Handtasche", "Rucksack", "Handbag", "Backpack"),
            new Pair("clothing-025", "Ohrring", "Halskette", "Earring", "Necklace"),
            new Pair("clothing-026", "Armband", "Fingerring", "Bracelet", "Ring"),
            new Pair("care-health-001", "Zahnbürste", "Zahnseide", "Toothbrush", "Dental floss"),
            new Pair("care-health-002", "Zahnpasta", "Mundspülung", "Toothpaste", "Mouthwash"),
            new Pair("care-health-003", "Seife", "Duschgel", "Soap", "Shower gel"),
            new Pair("care-health-004", "Shampoo", "Spülung", "Shampoo", "Hair conditioner"),
            new Pair("care-health-005", "Kamm", "Haarbürste", "Comb", "Hairbrush"),
            new Pair("care-health-006", "Föhn", "Glätteisen", "Hairdryer", "Hair straightener"),
            new Pair("care-health-007", "Rasierer", "Haarschneider", "Razor", "Hair clippers"),
            new Pair("care-health-008", "Nagelschere", "Nagelfeile", "Nail scissors", "Nail file"),
            new Pair("care-health-009", "Deodorant", "Parfüm", "Deodorant", "Perfume"),
            new Pair("care-health-010", "Handcreme", "Sonnencreme", "Hand cream", "Sunscreen"),
            new Pair("care-health-011", "Lippenbalsam", "Lippenstift", "Lip balm", "Lipstick"),
            new Pair("care-health-012", "Wimperntusche", "Lidschatten", "Mascara", "Eyeshadow"),
            new Pair("care-health-013", "Wattepad", "Wattestäbchen", "Cotton pad", "Cotton bud"),
            new Pair("care-health-014", "Handtuch", "Waschlappen", "Towel", "Washcloth"),
            new Pair("care-health-015", "Dusche", "Badewanne", "Shower", "Bathtub"),
            new Pair("care-health-016", "Waschbecken", "Bidet", "Washbasin", "Bidet"),
            new Pair("care-health-017", "Sauna", "Dampfbad", "Sauna", "Steam room"),
            new Pair("care-health-018", "Pflaster", "Verband", "Sticking plaster", "Bandage"),
            new Pair("care-health-019", "Krücke", "Gehstock", "Crutch", "Walking stick"),
            new Pair("care-health-020", "Sonnenbrille", "Kontaktlinse", "Sunglasses", "Contact lens"),
            new Pair("care-health-021", "Fieberthermometer", "Blutdruckmessgerät", "Medical thermometer", "Blood pressure monitor"),
            new Pair("care-health-022", "Wärmflasche", "Kühlpack", "Hot-water bottle", "Ice pack"),
            new Pair("care-health-023", "Tablette", "Hustensaft", "Pill", "Cough syrup"),
            new Pair("care-health-024", "Spritze", "Pipette", "Syringe", "Dropper"),
            new Pair("care-health-025", "Augenklappe", "Schlafmaske", "Eye patch", "Sleep mask"),
            new Pair("care-health-026", "Massage", "Gymnastik", "Massage", "Keep-fit exercises"),
            new Pair("mammals-001", "Hund", "Katze", "Dog", "Cat"),
            new Pair("mammals-002", "Wolf", "Fuchs", "Wolf", "Fox"),
            new Pair("mammals-003", "Löwe", "Tiger", "Lion", "Tiger"),
            new Pair("mammals-004", "Leopard", "Gepard", "Leopard", "Cheetah"),
            new Pair("mammals-005", "Jaguar", "Puma", "Jaguar", "Cougar"),
            new Pair("mammals-006", "Bär", "Gorilla", "Bear", "Gorilla"),
            new Pair("mammals-007", "Eisbär", "Panda", "Polar bear", "Panda"),
            new Pair("mammals-008", "Schimpanse", "Orang-Utan", "Chimpanzee", "Orangutan"),
            new Pair("mammals-009", "Pavian", "Lemur", "Baboon", "Lemur"),
            new Pair("mammals-010", "Elefant", "Nashorn", "Elephant", "Rhinoceros"),
            new Pair("mammals-011", "Nilpferd", "Nashorn", "Hippopotamus", "Rhinoceros"),
            new Pair("mammals-012", "Giraffe", "Zebra", "Giraffe", "Zebra"),
            new Pair("mammals-013", "Pferd", "Esel", "Horse", "Donkey"),
            new Pair("mammals-014", "Kuh", "Büffel", "Cow", "Buffalo"),
            new Pair("mammals-015", "Schaf", "Ziege", "Sheep", "Goat"),
            new Pair("mammals-016", "Schwein", "Wildschwein", "Pig", "Wild boar"),
            new Pair("mammals-017", "Hirsch", "Wildschwein", "Deer", "Wild boar"),
            new Pair("mammals-018", "Rentier", "Elch", "Reindeer", "Moose"),
            new Pair("mammals-019", "Kamel", "Lama", "Camel", "Llama"),
            new Pair("mammals-020", "Känguru", "Koala", "Kangaroo", "Koala"),
            new Pair("mammals-021", "Hase", "Kaninchen", "Hare", "Rabbit"),
            new Pair("mammals-022", "Hamster", "Meerschweinchen", "Hamster", "Guinea pig"),
            new Pair("mammals-023", "Maus", "Ratte", "Mouse", "Rat"),
            new Pair("mammals-024", "Eichhörnchen", "Streifenhörnchen", "Squirrel", "Chipmunk"),
            new Pair("mammals-025", "Igel", "Maulwurf", "Hedgehog", "Mole"),
            new Pair("mammals-026", "Biber", "Otter", "Beaver", "Otter"),
            new Pair("birds-water-creatures-001", "Ente", "Gans", "Duck", "Goose"),
            new Pair("birds-water-creatures-002", "Huhn", "Truthahn", "Chicken", "Turkey"),
            new Pair("birds-water-creatures-003", "Taube", "Möwe", "Pigeon", "Seagull"),
            new Pair("birds-water-creatures-004", "Spatz", "Rotkehlchen", "Sparrow", "Robin"),
            new Pair("birds-water-creatures-005", "Amsel", "Kanarienvogel", "Blackbird", "Canary"),
            new Pair("birds-water-creatures-006", "Adler", "Falke", "Eagle", "Falcon"),
            new Pair("birds-water-creatures-007", "Eule", "Fledermaus", "Owl", "Bat"),
            new Pair("birds-water-creatures-008", "Kakadu", "Wellensittich", "Cockatoo", "Budgerigar"),
            new Pair("birds-water-creatures-009", "Pfau", "Flamingo", "Peacock", "Flamingo"),
            new Pair("birds-water-creatures-010", "Strauß", "Pinguin", "Ostrich", "Penguin"),
            new Pair("birds-water-creatures-011", "Schwan", "Pelikan", "Swan", "Pelican"),
            new Pair("birds-water-creatures-012", "Storch", "Reiher", "Stork", "Heron"),
            new Pair("birds-water-creatures-013", "Specht", "Eisvogel", "Woodpecker", "Kingfisher"),
            new Pair("birds-water-creatures-014", "Rabe", "Elster", "Raven", "Magpie"),
            new Pair("birds-water-creatures-015", "Delfin", "Wal", "Dolphin", "Whale"),
            new Pair("birds-water-creatures-016", "Robbe", "Walross", "Seal", "Walrus"),
            new Pair("birds-water-creatures-017", "Hai", "Rochen", "Shark", "Ray"),
            new Pair("birds-water-creatures-018", "Lachs", "Forelle", "Salmon", "Trout"),
            new Pair("birds-water-creatures-019", "Thunfisch", "Schwertfisch", "Tuna", "Swordfish"),
            new Pair("birds-water-creatures-020", "Goldfisch", "Karpfen", "Goldfish", "Carp"),
            new Pair("birds-water-creatures-021", "Seepferdchen", "Seestern", "Seahorse", "Starfish"),
            new Pair("birds-water-creatures-022", "Qualle", "Krake", "Jellyfish", "Octopus"),
            new Pair("birds-water-creatures-023", "Krabbe", "Hummer", "Crab", "Lobster"),
            new Pair("birds-water-creatures-024", "Auster", "Garnele", "Oyster", "Prawn"),
            new Pair("birds-water-creatures-025", "Schildkröte", "Krokodil", "Turtle", "Crocodile"),
            new Pair("birds-water-creatures-026", "Schwertwal", "Narwal", "Killer whale", "Narwhal"),
            new Pair("garden-nature-001", "Rose", "Tulpe", "Rose", "Tulip"),
            new Pair("garden-nature-002", "Sonnenblume", "Gänseblümchen", "Sunflower", "Daisy"),
            new Pair("garden-nature-003", "Orchidee", "Lilie", "Orchid", "Lily"),
            new Pair("garden-nature-004", "Kaktus", "Palme", "Cactus", "Palm tree"),
            new Pair("garden-nature-005", "Farn", "Moos", "Fern", "Moss"),
            new Pair("garden-nature-006", "Eiche", "Buche", "Oak", "Beech"),
            new Pair("garden-nature-007", "Ahorn", "Kastanie", "Maple", "Chestnut tree"),
            new Pair("garden-nature-008", "Tanne", "Kiefer", "Fir tree", "Pine tree"),
            new Pair("garden-nature-009", "Birke", "Weide", "Birch", "Willow"),
            new Pair("garden-nature-010", "Bambus", "Schilf", "Bamboo", "Reed"),
            new Pair("garden-nature-011", "Klee", "Löwenzahn", "Clover", "Dandelion"),
            new Pair("garden-nature-012", "Lavendel", "Rosmarin", "Lavender", "Rosemary"),
            new Pair("garden-nature-013", "Basilikum", "Petersilie", "Basil", "Parsley"),
            new Pair("garden-nature-014", "Minze", "Salbei", "Mint", "Sage"),
            new Pair("garden-nature-015", "Wurzel", "Ast", "Root", "Branch"),
            new Pair("garden-nature-016", "Blatt", "Blüte", "Leaf", "Blossom"),
            new Pair("garden-nature-017", "Kiefernzapfen", "Eichel", "Pine cone", "Acorn"),
            new Pair("garden-nature-018", "Biene", "Wespe", "Bee", "Wasp"),
            new Pair("garden-nature-019", "Hummel", "Hornisse", "Bumblebee", "Hornet"),
            new Pair("garden-nature-020", "Schmetterling", "Libelle", "Butterfly", "Dragonfly"),
            new Pair("garden-nature-021", "Ameise", "Termite", "Ant", "Termite"),
            new Pair("garden-nature-022", "Käfer", "Grashüpfer", "Beetle", "Grasshopper"),
            new Pair("garden-nature-023", "Schnecke", "Regenwurm", "Snail", "Earthworm"),
            new Pair("garden-nature-024", "Spinne", "Skorpion", "Spider", "Scorpion"),
            new Pair("garden-nature-025", "Frosch", "Kröte", "Frog", "Toad"),
            new Pair("garden-nature-026", "Eidechse", "Salamander", "Lizard", "Salamander"),
            new Pair("landscape-weather-001", "Berg", "Hügel", "Mountain", "Hill"),
            new Pair("landscape-weather-002", "Tal", "Schlucht", "Valley", "Gorge"),
            new Pair("landscape-weather-003", "Wald", "Dschungel", "Forest", "Jungle"),
            new Pair("landscape-weather-004", "Wiese", "Feld", "Meadow", "Field"),
            new Pair("landscape-weather-005", "Wüste", "Savanne", "Desert", "Savannah"),
            new Pair("landscape-weather-006", "Insel", "Halbinsel", "Island", "Peninsula"),
            new Pair("landscape-weather-007", "Strand", "Küste", "Beach", "Coast"),
            new Pair("landscape-weather-008", "See", "Teich", "Lake", "Pond"),
            new Pair("landscape-weather-009", "Fluss", "Bach", "River", "Stream"),
            new Pair("landscape-weather-010", "Wasserfall", "Stromschnelle", "Waterfall", "Rapids"),
            new Pair("landscape-weather-011", "Höhle", "Tunnel", "Cave", "Tunnel"),
            new Pair("landscape-weather-012", "Vulkan", "Geysir", "Volcano", "Geyser"),
            new Pair("landscape-weather-013", "Gletscher", "Eisberg", "Glacier", "Iceberg"),
            new Pair("landscape-weather-014", "Korallenriff", "Sandbank", "Coral reef", "Sandbank"),
            new Pair("landscape-weather-015", "Sumpf", "Moor", "Swamp", "Bog"),
            new Pair("landscape-weather-016", "Düne", "Klippe", "Sand dune", "Cliff"),
            new Pair("landscape-weather-017", "Regen", "Schnee", "Rain", "Snow"),
            new Pair("landscape-weather-018", "Hagel", "Schneeregen", "Hail", "Sleet"),
            new Pair("landscape-weather-019", "Nebel", "Wolke", "Fog", "Cloud"),
            new Pair("landscape-weather-020", "Blitz", "Donner", "Lightning", "Thunder"),
            new Pair("landscape-weather-021", "Sturm", "Tornado", "Storm", "Tornado"),
            new Pair("landscape-weather-022", "Regenbogen", "Polarlicht", "Rainbow", "Northern lights"),
            new Pair("landscape-weather-023", "Sonnenaufgang", "Sonnenuntergang", "Sunrise", "Sunset"),
            new Pair("landscape-weather-024", "Tau", "Reif", "Dew", "Frost"),
            new Pair("landscape-weather-025", "Flut", "Ebbe", "High tide", "Low tide"),
            new Pair("landscape-weather-026", "Lawine", "Erdrutsch", "Avalanche", "Landslide"),
            new Pair("transport-travel-001", "Auto", "Motorrad", "Car", "Motorcycle"),
            new Pair("transport-travel-002", "Fahrrad", "Tretroller", "Bicycle", "Kick scooter"),
            new Pair("transport-travel-003", "Bus", "Straßenbahn", "Bus", "Tram"),
            new Pair("transport-travel-004", "Regionalzug", "U-Bahn", "Regional train", "Underground train"),
            new Pair("transport-travel-005", "Taxi", "Mietwagen", "Taxi", "Hire car"),
            new Pair("transport-travel-006", "Lastwagen", "Lieferwagen", "Lorry", "Delivery van"),
            new Pair("transport-travel-007", "Traktor", "Mähdrescher", "Tractor", "Combine harvester"),
            new Pair("transport-travel-008", "Wohnmobil", "Wohnwagen", "Motorhome", "Caravan"),
            new Pair("transport-travel-009", "Krankenwagen", "Feuerwehrauto", "Ambulance", "Fire engine"),
            new Pair("transport-travel-010", "Rennwagen", "Kart", "Racing car", "Go-kart"),
            new Pair("transport-travel-011", "Limousine", "Geländewagen", "Limousine", "Off-road vehicle"),
            new Pair("transport-travel-012", "Roller", "Moped", "Motor scooter", "Moped"),
            new Pair("transport-travel-013", "Flugzeug", "Hubschrauber", "Aeroplane", "Helicopter"),
            new Pair("transport-travel-014", "Heißluftballon", "Luftschiff", "Hot-air balloon", "Airship"),
            new Pair("transport-travel-015", "Segelflugzeug", "Drachenflieger", "Glider", "Hang glider"),
            new Pair("transport-travel-016", "Segelboot", "Motorboot", "Sailing boat", "Motorboat"),
            new Pair("transport-travel-017", "Kanu", "Ruderboot", "Canoe", "Rowing boat"),
            new Pair("transport-travel-018", "Fähre", "Kreuzfahrtschiff", "Ferry", "Cruise ship"),
            new Pair("transport-travel-019", "U-Boot", "Containerschiff", "Submarine", "Container ship"),
            new Pair("transport-travel-020", "Seilbahn", "Sessellift", "Cable car", "Chairlift"),
            new Pair("transport-travel-021", "Rolltreppe", "Aufzug", "Escalator", "Lift"),
            new Pair("transport-travel-022", "Koffer", "Reisetasche", "Suitcase", "Travel bag"),
            new Pair("transport-travel-023", "Reisepass", "Personalausweis", "Passport", "Identity card"),
            new Pair("transport-travel-024", "Fahrkarte", "Bordkarte", "Travel ticket", "Boarding pass"),
            new Pair("transport-travel-025", "Landkarte", "Globus", "Map", "Globe"),
            new Pair("transport-travel-026", "Kompass", "Navigationsgerät", "Compass", "Satnav"),
            new Pair("places-001", "Bahnhof", "Flughafen", "Railway station", "Airport"),
            new Pair("places-002", "Bushaltestelle", "Taxistand", "Bus stop", "Taxi rank"),
            new Pair("places-003", "Hafen", "Yachthafen", "Port", "Marina"),
            new Pair("places-004", "Parkhaus", "Parkplatz", "Multi-storey car park", "Car park"),
            new Pair("places-005", "Hängebrücke", "Zugbrücke", "Suspension bridge", "Drawbridge"),
            new Pair("places-006", "Kreuzung", "Kreisverkehr", "Crossroads", "Roundabout"),
            new Pair("places-007", "Gehweg", "Radweg", "Pavement", "Cycle path"),
            new Pair("places-008", "Zebrastreifen", "Fußgängerampel", "Zebra crossing", "Pedestrian traffic light"),
            new Pair("places-009", "Bäckerei", "Metzgerei", "Bakery", "Butcher's shop"),
            new Pair("places-010", "Supermarkt", "Wochenmarkt", "Supermarket", "Street market"),
            new Pair("places-011", "Restaurant", "Café", "Restaurant", "Café"),
            new Pair("places-012", "Hotel", "Jugendherberge", "Hotel", "Youth hostel"),
            new Pair("places-013", "Campingplatz", "Ferienwohnung", "Campsite", "Holiday apartment"),
            new Pair("places-014", "Museum", "Kunstgalerie", "Museum", "Art gallery"),
            new Pair("places-015", "Kino", "Theater", "Cinema", "Theatre"),
            new Pair("places-016", "Bibliothek", "Buchhandlung", "Library", "Bookshop"),
            new Pair("places-017", "Schule", "Kindergarten", "School", "Nursery school"),
            new Pair("places-018", "Krankenhaus", "Arztpraxis", "Hospital", "Doctor's surgery"),
            new Pair("places-019", "Apotheke", "Parfümerie", "Pharmacy", "Perfume shop"),
            new Pair("places-020", "Rathaus", "Gerichtsgebäude", "Town hall", "Courthouse"),
            new Pair("places-021", "Polizeiwache", "Feuerwache", "Police station", "Fire station"),
            new Pair("places-022", "Postamt", "Bankfiliale", "Post office", "Bank branch"),
            new Pair("places-023", "Zoo", "Aquarium", "Zoo", "Aquarium"),
            new Pair("places-024", "Spielplatz", "Freizeitpark", "Playground", "Theme park"),
            new Pair("places-025", "Schloss", "Burg", "Palace", "Castle"),
            new Pair("places-026", "Leuchtturm", "Aussichtsturm", "Lighthouse", "Observation tower"),
            new Pair("school-office-001", "Bleistift", "Kugelschreiber", "Pencil", "Ballpoint pen"),
            new Pair("school-office-002", "Füller", "Filzstift", "Fountain pen", "Felt-tip pen"),
            new Pair("school-office-003", "Buntstift", "Wachsmalstift", "Coloured pencil", "Wax crayon"),
            new Pair("school-office-004", "Radiergummi", "Spitzer", "Eraser", "Pencil sharpener"),
            new Pair("school-office-005", "Lineal", "Geodreieck", "Ruler", "Set square"),
            new Pair("school-office-006", "Zirkel", "Winkelmesser", "Drawing compass", "Protractor"),
            new Pair("school-office-007", "Heft", "Notizblock", "Exercise book", "Notepad"),
            new Pair("school-office-008", "Ordner", "Schnellhefter", "Ring binder", "Document folder"),
            new Pair("school-office-009", "Briefumschlag", "Postkarte", "Envelope", "Postcard"),
            new Pair("school-office-010", "Büroklammer", "Heftklammer", "Paper clip", "Staple"),
            new Pair("school-office-011", "Tacker", "Locher", "Stapler", "Hole punch"),
            new Pair("school-office-012", "Klebeband", "Klebestift", "Sticky tape", "Glue stick"),
            new Pair("school-office-013", "Korrekturroller", "Textmarker", "Correction tape", "Highlighter"),
            new Pair("school-office-014", "Schultafel", "Whiteboard", "Blackboard", "Whiteboard"),
            new Pair("school-office-015", "Kreide", "Schwamm", "Chalk", "Sponge"),
            new Pair("school-office-016", "Schulranzen", "Federmäppchen", "School bag", "Pencil case"),
            new Pair("school-office-017", "Taschenrechner", "Abakus", "Calculator", "Abacus"),
            new Pair("school-office-018", "Wörterbuch", "Lexikon", "Dictionary", "Encyclopaedia"),
            new Pair("school-office-019", "Atlas", "Stadtplan", "Atlas", "City map"),
            new Pair("school-office-020", "Stundenplan", "Kalender", "Timetable", "Calendar"),
            new Pair("school-office-021", "Hausaufgabe", "Klassenarbeit", "Homework", "Class test"),
            new Pair("school-office-022", "Zeugnis", "Urkunde", "School report", "Certificate"),
            new Pair("school-office-023", "Referat", "Aufsatz", "Oral presentation", "Essay"),
            new Pair("school-office-024", "Lesebrille", "Lupe", "Reading glasses", "Magnifying glass"),
            new Pair("school-office-025", "Aktenschrank", "Schließfach", "Filing cabinet", "Locker"),
            new Pair("school-office-026", "Stempel", "Wachssiegel", "Rubber stamp", "Wax seal"),
            new Pair("tools-materials-001", "Hammer", "Schraubendreher", "Hammer", "Screwdriver"),
            new Pair("tools-materials-002", "Nagel", "Schraube", "Nail", "Screw"),
            new Pair("tools-materials-003", "Dübel", "Haken", "Wall plug", "Hook"),
            new Pair("tools-materials-004", "Zange", "Schraubenschlüssel", "Pliers", "Spanner"),
            new Pair("tools-materials-005", "Säge", "Axt", "Saw", "Axe"),
            new Pair("tools-materials-006", "Bohrmaschine", "Akkuschrauber", "Drill", "Electric screwdriver"),
            new Pair("tools-materials-007", "Schleifpapier", "Feile", "Sandpaper", "File"),
            new Pair("tools-materials-008", "Pinsel", "Farbrolle", "Paintbrush", "Paint roller"),
            new Pair("tools-materials-009", "Wasserwaage", "Maßband", "Spirit level", "Tape measure"),
            new Pair("tools-materials-010", "Schraubstock", "Schraubzwinge", "Vice", "Clamp"),
            new Pair("tools-materials-011", "Werkbank", "Staffelei", "Workbench", "Easel"),
            new Pair("tools-materials-012", "Schubkarre", "Bollerwagen", "Wheelbarrow", "Handcart"),
            new Pair("tools-materials-013", "Schaufel", "Spaten", "Shovel", "Spade"),
            new Pair("tools-materials-014", "Rechen", "Mistgabel", "Rake", "Pitchfork"),
            new Pair("tools-materials-015", "Gartenschlauch", "Gießkanne", "Garden hose", "Watering can"),
            new Pair("tools-materials-016", "Rasenmäher", "Heckenschere", "Lawnmower", "Hedge trimmer"),
            new Pair("tools-materials-017", "Laubbläser", "Hochdruckreiniger", "Leaf blower", "Pressure washer"),
            new Pair("tools-materials-018", "Arbeitshandschuh", "Schutzbrille", "Work glove", "Safety goggles"),
            new Pair("tools-materials-019", "Schutzhelm", "Sonnenhut", "Hard hat", "Sun hat"),
            new Pair("tools-materials-020", "Seil", "Kette", "Rope", "Chain"),
            new Pair("tools-materials-021", "Klebstoff", "Silikon", "Glue", "Silicone sealant"),
            new Pair("tools-materials-022", "Beton", "Gips", "Concrete", "Plaster of Paris"),
            new Pair("tools-materials-023", "Ziegel", "Pflasterstein", "Brick", "Paving stone"),
            new Pair("tools-materials-024", "Holz", "Metall", "Wood", "Metal"),
            new Pair("tools-materials-025", "Glas", "Kunststoff", "Glass", "Plastic"),
            new Pair("tools-materials-026", "Kran", "Bagger", "Crane", "Excavator"),
            new Pair("sports-001", "Fußball", "Basketball", "Football", "Basketball"),
            new Pair("sports-002", "Handball", "Volleyball", "Team handball", "Volleyball"),
            new Pair("sports-003", "Tennis", "Badminton", "Tennis", "Badminton"),
            new Pair("sports-004", "Tischtennis", "Squash", "Table tennis", "Squash"),
            new Pair("sports-005", "Golf", "Minigolf", "Golf", "Miniature golf"),
            new Pair("sports-006", "Rugby", "American Football", "Rugby", "American football"),
            new Pair("sports-007", "Baseball", "Cricket", "Baseball", "Cricket"),
            new Pair("sports-008", "Hockey", "Eishockey", "Field hockey", "Ice hockey"),
            new Pair("sports-009", "Skifahren", "Snowboarden", "Skiing", "Snowboarding"),
            new Pair("sports-010", "Schlittschuhlaufen", "Inlineskaten", "Ice skating", "Inline skating"),
            new Pair("sports-011", "Surfen", "Windsurfen", "Surfing", "Windsurfing"),
            new Pair("sports-012", "Schwimmen", "Schnorcheln", "Swimming", "Snorkelling"),
            new Pair("sports-013", "Rudern", "Paddeln", "Rowing", "Paddling"),
            new Pair("sports-014", "Segeln", "Wasserski", "Sailing", "Water skiing"),
            new Pair("sports-015", "Joggen", "Wandern", "Jogging", "Hiking"),
            new Pair("sports-016", "Sprint", "Marathon", "Sprint", "Marathon"),
            new Pair("sports-017", "Hochsprung", "Weitsprung", "High jump", "Long jump"),
            new Pair("sports-018", "Speerwurf", "Diskuswurf", "Javelin throw", "Discus throw"),
            new Pair("sports-019", "Boxen", "Ringen", "Boxing", "Wrestling"),
            new Pair("sports-020", "Judo", "Karate", "Judo", "Karate"),
            new Pair("sports-021", "Fechten", "Bogenschießen", "Fencing", "Archery"),
            new Pair("sports-022", "Reiten", "Radfahren", "Horse riding", "Cycling"),
            new Pair("sports-023", "Kletterwand", "Trampolin", "Climbing wall", "Trampoline"),
            new Pair("sports-024", "Yoga", "Pilates", "Yoga", "Pilates"),
            new Pair("sports-025", "Liegestütz", "Kniebeuge", "Push-up", "Squat"),
            new Pair("sports-026", "Hantel", "Medizinball", "Dumbbell", "Medicine ball"),
            new Pair("arts-media-001", "Gitarre", "Geige", "Guitar", "Violin"),
            new Pair("arts-media-002", "Klavier", "Orgel", "Piano", "Organ"),
            new Pair("arts-media-003", "Trompete", "Posaune", "Trumpet", "Trombone"),
            new Pair("arts-media-004", "Flöte", "Klarinette", "Flute", "Clarinet"),
            new Pair("arts-media-005", "Saxophon", "Akkordeon", "Saxophone", "Accordion"),
            new Pair("arts-media-006", "Trommel", "Xylophon", "Drum", "Xylophone"),
            new Pair("arts-media-007", "Harfe", "Kontrabass", "Harp", "Double bass"),
            new Pair("arts-media-008", "Schlagzeug", "Tamburin", "Drum kit", "Tambourine"),
            new Pair("arts-media-009", "Mikrofon", "Megafon", "Microphone", "Megaphone"),
            new Pair("arts-media-010", "Lautsprecher", "Kopfhörer", "Loudspeaker", "Headphones"),
            new Pair("arts-media-011", "Notenblatt", "Liedtext", "Sheet music", "Song lyrics"),
            new Pair("arts-media-012", "Dirigent", "Komponist", "Conductor", "Composer"),
            new Pair("arts-media-013", "Sänger", "Tänzer", "Singer", "Dancer"),
            new Pair("arts-media-014", "Schauspieler", "Zauberer", "Actor", "Magician"),
            new Pair("arts-media-015", "Chor", "Orchester", "Choir", "Orchestra"),
            new Pair("arts-media-016", "Konzert", "Musical", "Concert", "Musical"),
            new Pair("arts-media-017", "Oper", "Ballett", "Opera", "Ballet"),
            new Pair("arts-media-018", "Film", "Serie", "Film", "TV series"),
            new Pair("arts-media-019", "Dokumentarfilm", "Zeichentrickfilm", "Documentary", "Animated film"),
            new Pair("arts-media-020", "Roman", "Comic", "Novel", "Comic"),
            new Pair("arts-media-021", "Gedicht", "Märchen", "Poem", "Fairy tale"),
            new Pair("arts-media-022", "Zeitung", "Zeitschrift", "Newspaper", "Magazine"),
            new Pair("arts-media-023", "Hörbuch", "Podcast", "Audiobook", "Podcast"),
            new Pair("arts-media-024", "Radio", "Fernsehen", "Radio", "Television"),
            new Pair("arts-media-025", "Ölgemälde", "Aquarell", "Oil painting", "Watercolour painting"),
            new Pair("arts-media-026", "Skulptur", "Mosaik", "Sculpture", "Mosaic"),
            new Pair("games-leisure-001", "Schach", "Dame", "Chess", "Draughts"),
            new Pair("games-leisure-002", "Domino", "Mahjong", "Dominoes", "Mahjong"),
            new Pair("games-leisure-003", "Puzzle", "Bauklötze", "Jigsaw puzzle", "Building blocks"),
            new Pair("games-leisure-004", "Kartenspiel", "Brettspiel", "Card game", "Board game"),
            new Pair("games-leisure-005", "Würfel", "Münze", "Die", "Coin"),
            new Pair("games-leisure-006", "Murmel", "Flummi", "Marble", "Bouncy ball"),
            new Pair("games-leisure-007", "Jojo", "Kreisel", "Yo-yo", "Spinning top"),
            new Pair("games-leisure-008", "Seifenblasen", "Luftballon", "Soap bubbles", "Balloon"),
            new Pair("games-leisure-009", "Drachen", "Papierflieger", "Toy kite", "Paper aeroplane"),
            new Pair("games-leisure-010", "Schaukel", "Wippe", "Swing", "Seesaw"),
            new Pair("games-leisure-011", "Rutsche", "Karussell", "Slide", "Merry-go-round"),
            new Pair("games-leisure-012", "Sandburg", "Schneemann", "Sandcastle", "Snowman"),
            new Pair("games-leisure-013", "Verstecken", "Fangen", "Hide-and-seek", "Tag"),
            new Pair("games-leisure-014", "Seilziehen", "Sackhüpfen", "Tug of war", "Sack race"),
            new Pair("games-leisure-015", "Hüpfkästchen", "Eierlauf", "Hopscotch", "Egg-and-spoon race"),
            new Pair("games-leisure-016", "Hula-Hoop-Reifen", "Springseil", "Hula hoop", "Skipping rope"),
            new Pair("games-leisure-017", "Stricken", "Häkeln", "Knitting", "Crochet"),
            new Pair("games-leisure-018", "Nähen", "Sticken", "Sewing", "Embroidery"),
            new Pair("games-leisure-019", "Töpfern", "Schnitzen", "Pottery", "Woodcarving"),
            new Pair("games-leisure-020", "Origami", "Papiermaché", "Origami", "Papier-mâché"),
            new Pair("games-leisure-021", "Basteln", "Malen", "Crafting", "Painting"),
            new Pair("games-leisure-022", "Fotografieren", "Filmen", "Taking photos", "Filming"),
            new Pair("games-leisure-023", "Angeln", "Pilze sammeln", "Fishing", "Mushroom picking"),
            new Pair("games-leisure-024", "Picknick", "Grillen", "Picnic", "Barbecue"),
            new Pair("games-leisure-025", "Zelt", "Schlafsack", "Tent", "Sleeping bag"),
            new Pair("games-leisure-026", "Fernglas", "Teleskop", "Binoculars", "Telescope"),
            new Pair("technology-001", "Smartphone", "Tablet", "Smartphone", "Tablet"),
            new Pair("technology-002", "Laptop", "Desktop-PC", "Laptop", "Desktop PC"),
            new Pair("technology-003", "Tastatur", "Computermaus", "Keyboard", "Computer mouse"),
            new Pair("technology-004", "Bildschirm", "Projektor", "Monitor", "Projector"),
            new Pair("technology-005", "Drucker", "Scanner", "Printer", "Scanner"),
            new Pair("technology-006", "USB-Stick", "Speicherkarte", "USB flash drive", "Memory card"),
            new Pair("technology-007", "Festplatte", "DVD", "Hard drive", "DVD"),
            new Pair("technology-008", "Ladekabel", "Steckdose", "Charging cable", "Power socket"),
            new Pair("technology-009", "Batterie", "Akku", "Disposable battery", "Rechargeable battery"),
            new Pair("technology-010", "Powerbank", "Ladestation", "Power bank", "Charging dock"),
            new Pair("technology-011", "Fernbedienung", "Controller", "Remote control", "Game controller"),
            new Pair("technology-012", "Spielkonsole", "Spielautomat", "Games console", "Arcade machine"),
            new Pair("technology-013", "Smartwatch", "Schrittzähler", "Smartwatch", "Pedometer"),
            new Pair("technology-014", "Digitalkamera", "Sofortbildkamera", "Digital camera", "Instant camera"),
            new Pair("technology-015", "Videokamera", "Webcam", "Camcorder", "Webcam"),
            new Pair("technology-016", "Stativ", "Selfiestick", "Tripod", "Selfie stick"),
            new Pair("technology-017", "Wecker", "Stoppuhr", "Alarm clock", "Stopwatch"),
            new Pair("technology-018", "Sanduhr", "Sonnenuhr", "Hourglass", "Sundial"),
            new Pair("technology-019", "Türklingel", "Alarmanlage", "Doorbell", "Burglar alarm"),
            new Pair("technology-020", "Rauchmelder", "Bewegungsmelder", "Smoke detector", "Motion sensor"),
            new Pair("technology-021", "Taschenlampe", "Laterne", "Torch", "Lantern"),
            new Pair("technology-022", "E-Mail", "SMS", "Email", "Text message"),
            new Pair("technology-023", "Sprachnachricht", "Videoanruf", "Voice message", "Video call"),
            new Pair("technology-024", "Passwort", "PIN", "Password", "PIN"),
            new Pair("technology-025", "Suchmaschine", "Webbrowser", "Search engine", "Web browser"),
            new Pair("technology-026", "Roboter", "Drohne", "Robot", "Drone"),
        };
    }
}
