"""Generate pinned Unicode 17.0.0 name properties; no dependencies beyond Python 3."""
import argparse
import hashlib
import shutil
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCES = {
    "GraphemeBreakProperty.txt": ("auxiliary/GraphemeBreakProperty.txt", "d6b51d1d2ae5c33b451b7ed994b48f1f4dc62b2272a5831e7fd418514a6bae89"),
    "emoji-data.txt": ("emoji/emoji-data.txt", "2cb2bb9455cda83e8481541ecf5b6dfda66a3bb89efa3fa7c5297eccf607b72b"),
    "DerivedCoreProperties.txt": ("DerivedCoreProperties.txt", "24c7fed1195c482faaefd5c1e7eb821c5ee1fb6de07ecdbaa64b56a99da22c08"),
    "UnicodeData.txt": ("UnicodeData.txt", "2e1efc1dcb59c575eedf5ccae60f95229f706ee6d031835247d843c11d96470c"),
    "GraphemeBreakTest.txt": ("auxiliary/GraphemeBreakTest.txt", "e2d134d2c52919bace503ebb6a551c1855fe1a1faec18478c78fff254a1793ec"),
    "LICENSE.txt": ("https://www.unicode.org/license.txt", "e7a93b009565cfce55919a381437ac4db883e9da2126fa28b91d12732bc53d96"),
}
GCB = {name: number for number, name in enumerate(
    ("Other", "CR", "LF", "Control", "Extend", "ZWJ", "Regional_Indicator", "Prepend", "SpacingMark", "L", "V", "T", "LV", "LVT"))}
INCB = {"Consonant": 32, "Extend": 64, "Linker": 96}
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("--cache", type=Path, default=ROOT / "artifacts/unicode-17")
parser.add_argument("--download", action="store_true")
args = parser.parse_args()
args.cache.mkdir(parents=True, exist_ok=True)
for name, (suffix, expected) in SOURCES.items():
    path = args.cache / name
    if args.download:
        url = suffix if suffix.startswith("https:") else "https://www.unicode.org/Public/17.0.0/ucd/" + suffix
        path.write_bytes(urllib.request.urlopen(url).read())
    actual = hashlib.sha256(path.read_bytes()).hexdigest()
    if actual != expected:
        raise ValueError(f"Untrusted input {name}: expected {expected}, got {actual}")

def properties(name):
    for line in (args.cache / name).read_text(encoding="utf-8").splitlines():
        parts = [part.strip() for part in line.split("#", 1)[0].split(";")]
        if len(parts) < 2:
            continue
        ends = parts[0].split("..")
        yield int(ends[0], 16), int(ends[-1], 16), parts[1:]

# Bit 7 marks scalars that cannot be the visible base of a new player name.
# Unassigned scalars default to this state. Co (private use) remains allowed.
values = bytearray([128]) * 0x110000
first = None
for line in (args.cache / "UnicodeData.txt").read_text(encoding="utf-8").splitlines():
    parts = line.split(";")
    scalar, name, category = int(parts[0], 16), parts[1], parts[2]
    invisible = category[0] in "MZ" or category in ("Cc", "Cf", "Cs", "Cn")
    if name.endswith(", First>"):
        first = scalar
    else:
        start = first if name.endswith(", Last>") else scalar
        values[start:scalar + 1] = bytes([128 if invisible else 0]) * (scalar + 1 - start)
        first = None
for start, end, props in properties("GraphemeBreakProperty.txt"):
    for scalar in range(start, end + 1):
        values[scalar] |= GCB[props[0]]
for start, end, props in properties("emoji-data.txt"):
    if props[0] == "Extended_Pictographic":
        for scalar in range(start, end + 1):
            values[scalar] |= 16
for start, end, props in properties("DerivedCoreProperties.txt"):
    flag = 128 if props[0] == "Default_Ignorable_Code_Point" else INCB[props[1]] if props[0] == "InCB" else 0
    if flag:
        for scalar in range(start, end + 1):
            values[scalar] |= flag

ranges = []
start = 0
for scalar in range(1, len(values) + 1):
    if scalar == len(values) or values[scalar] != values[start]:
        if values[start]:
            ranges.append(f"            0x{start:X}, 0x{scalar - 1:X}, {values[start]},")
        start = scalar
output = """// Generated by tools/generate-name-unicode.py from Unicode 17.0.0.
// Unicode data copyright and license: third-party/unicode-17.0.0/LICENSE.txt.
// Reproduce and verify pinned source hashes with the generator; do not edit.
namespace WordDeduction
{
    public static partial class NameText
    {
        // Inclusive start, inclusive end, GCB | Extended_Pictographic | InCB | invisible-base.
        private static readonly int[] PropertyRanges = {
%s
        };
    }
}
""" % "\n".join(ranges)
(ROOT / "game/Assets/WordDeduction/Session/NameText.Data.cs").write_text(output, encoding="utf-8", newline="\n")
destination = ROOT / "third-party/unicode-17.0.0"
destination.mkdir(parents=True, exist_ok=True)
for name in ("GraphemeBreakTest.txt", "LICENSE.txt"):
    shutil.copyfile(args.cache / name, destination / name)
shutil.copyfile(args.cache / "LICENSE.txt", ROOT / "game/Assets/Resources/Unicode-LICENSE.txt")
print(f"Generated {len(ranges)} property ranges, {len(output)} source bytes; verified all six source hashes.")
